name: Release Drafter

on:
  push:
    branches:
      - latest
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        with:
          config-name: release-drafter.yml
        # with: release-drafter.yml
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
